title: Akshay Portfolio
description: Always excited to extract insights from data that bring value to business
google_analytics:
theme: jekyll-theme-hacker
github:
  repository_url: https://github.com/Akshaytank007
